import { Download, Printer, Share2 } from 'lucide-react'

export default function PDFReportPreview() {
  return (
    <div className="max-w-4xl mx-auto">
      {/* PDF Viewer Controls */}
      <div className="bg-gray-900 border border-white/10 rounded-t-xl p-4 flex items-center justify-between">
        <div className="text-sm text-gray-400">
          123-Main-St-Inspection-Report.pdf
        </div>
        <div className="flex items-center space-x-3">
          <button className="p-2 hover:bg-white/10 rounded-lg transition-colors">
            <Printer className="w-5 h-5 text-gray-400" />
          </button>
          <button className="p-2 hover:bg-white/10 rounded-lg transition-colors">
            <Share2 className="w-5 h-5 text-gray-400" />
          </button>
          <button className="px-4 py-2 bg-blue-600 hover:bg-blue-700 rounded-lg flex items-center space-x-2 transition-colors">
            <Download className="w-4 h-4" />
            <span className="text-sm font-medium">Download</span>
          </button>
        </div>
      </div>

      {/* PDF Content - Styled to look like a real PDF */}
      <div className="bg-white text-gray-900 shadow-2xl" style={{ aspectRatio: '8.5/11' }}>
        <div className="p-12 h-full overflow-auto">
          {/* Header */}
          <div className="border-b-4 border-blue-600 pb-6 mb-8">
            <div className="flex items-start justify-between">
              <div>
                <h1 className="text-3xl font-bold text-gray-900 mb-2">
                  Property Inspection Report
                </h1>
                <div className="text-sm text-gray-600">
                  Generated by InspectIQ AI • November 22, 2024
                </div>
              </div>
              <div className="text-right">
                <div className="text-2xl font-bold text-blue-600">InspectIQ</div>
                <div className="text-xs text-gray-500">AI-Powered Inspections</div>
              </div>
            </div>
          </div>

          {/* Property Information */}
          <div className="mb-8">
            <h2 className="text-xl font-bold text-gray-900 mb-4 border-l-4 border-blue-600 pl-3">
              Property Information
            </h2>
            <div className="grid grid-cols-2 gap-4 bg-gray-50 p-4 rounded-lg">
              <div>
                <div className="text-xs text-gray-500 uppercase mb-1">Address</div>
                <div className="font-semibold">123 Main Street, Apt 4B</div>
                <div className="text-sm text-gray-600">San Francisco, CA 94102</div>
              </div>
              <div>
                <div className="text-xs text-gray-500 uppercase mb-1">Inspection Date</div>
                <div className="font-semibold">November 22, 2024</div>
              </div>
              <div>
                <div className="text-xs text-gray-500 uppercase mb-1">Inspector</div>
                <div className="font-semibold">John Smith</div>
              </div>
              <div>
                <div className="text-xs text-gray-500 uppercase mb-1">Type</div>
                <div className="font-semibold">Move-In Inspection</div>
              </div>
            </div>
          </div>

          {/* Executive Summary */}
          <div className="mb-8">
            <h2 className="text-xl font-bold text-gray-900 mb-4 border-l-4 border-blue-600 pl-3">
              Executive Summary
            </h2>
            <div className="bg-blue-50 border-l-4 border-blue-600 p-4 rounded-r-lg mb-4">
              <div className="flex items-center justify-between mb-2">
                <span className="font-semibold text-gray-900">Overall Condition:</span>
                <span className="px-3 py-1 bg-orange-100 text-orange-800 rounded-full text-sm font-semibold">
                  Fair
                </span>
              </div>
              <div className="text-sm text-gray-700">
                Property shows normal wear and tear with 2 critical issues requiring immediate attention.
              </div>
            </div>
            
            <div className="grid grid-cols-3 gap-4">
              <div className="bg-red-50 p-4 rounded-lg border border-red-200">
                <div className="text-3xl font-bold text-red-600 mb-1">2</div>
                <div className="text-sm text-gray-700">Critical Issues</div>
              </div>
              <div className="bg-orange-50 p-4 rounded-lg border border-orange-200">
                <div className="text-3xl font-bold text-orange-600 mb-1">5</div>
                <div className="text-sm text-gray-700">Moderate Issues</div>
              </div>
              <div className="bg-yellow-50 p-4 rounded-lg border border-yellow-200">
                <div className="text-3xl font-bold text-yellow-600 mb-1">5</div>
                <div className="text-sm text-gray-700">Minor Issues</div>
              </div>
            </div>
          </div>

          {/* Room-by-Room Findings */}
          <div className="mb-8">
            <h2 className="text-xl font-bold text-gray-900 mb-4 border-l-4 border-blue-600 pl-3">
              Detailed Findings
            </h2>
            
            {/* Living Room */}
            <div className="mb-6">
              <h3 className="font-bold text-gray-900 mb-3 flex items-center">
                <span className="w-8 h-8 bg-blue-600 text-white rounded-full flex items-center justify-center text-sm mr-2">1</span>
                Living Room
              </h3>
              <div className="space-y-2 ml-10">
                <div className="flex items-start space-x-3 p-3 bg-red-50 border-l-4 border-red-500 rounded-r">
                  <div className="w-2 h-2 bg-red-500 rounded-full mt-2"></div>
                  <div className="flex-1">
                    <div className="font-semibold text-gray-900">Cracked window pane</div>
                    <div className="text-sm text-gray-600">Location: North-facing window</div>
                    <div className="text-xs text-red-600 mt-1">⚠️ CRITICAL - Immediate attention required</div>
                  </div>
                </div>
                <div className="flex items-start space-x-3 p-3 bg-orange-50 border-l-4 border-orange-500 rounded-r">
                  <div className="w-2 h-2 bg-orange-500 rounded-full mt-2"></div>
                  <div className="flex-1">
                    <div className="font-semibold text-gray-900">Paint chipping on baseboards</div>
                    <div className="text-sm text-gray-600">Location: East wall</div>
                  </div>
                </div>
              </div>
            </div>

            {/* Bathroom */}
            <div className="mb-6">
              <h3 className="font-bold text-gray-900 mb-3 flex items-center">
                <span className="w-8 h-8 bg-blue-600 text-white rounded-full flex items-center justify-center text-sm mr-2">2</span>
                Bathroom
              </h3>
              <div className="space-y-2 ml-10">
                <div className="flex items-start space-x-3 p-3 bg-red-50 border-l-4 border-red-500 rounded-r">
                  <div className="w-2 h-2 bg-red-500 rounded-full mt-2"></div>
                  <div className="flex-1">
                    <div className="font-semibold text-gray-900">Water damage on ceiling</div>
                    <div className="text-sm text-gray-600">Location: Above shower</div>
                    <div className="text-xs text-red-600 mt-1">⚠️ CRITICAL - Potential mold risk</div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* AI Recommendations */}
          <div className="mb-8">
            <h2 className="text-xl font-bold text-gray-900 mb-4 border-l-4 border-purple-600 pl-3">
              🤖 AI Recommendations
            </h2>
            <div className="bg-purple-50 p-4 rounded-lg border border-purple-200">
              <ul className="space-y-2">
                <li className="flex items-start space-x-2">
                  <span className="text-purple-600 font-bold">1.</span>
                  <span className="text-sm text-gray-700">Address water damage in bathroom immediately to prevent mold growth and structural issues</span>
                </li>
                <li className="flex items-start space-x-2">
                  <span className="text-purple-600 font-bold">2.</span>
                  <span className="text-sm text-gray-700">Replace cracked window pane for security and energy efficiency</span>
                </li>
                <li className="flex items-start space-x-2">
                  <span className="text-purple-600 font-bold">3.</span>
                  <span className="text-sm text-gray-700">Estimated repair cost: $800 - $1,200</span>
                </li>
              </ul>
            </div>
          </div>

          {/* Footer */}
          <div className="border-t-2 border-gray-200 pt-6 mt-8">
            <div className="flex items-center justify-between text-xs text-gray-500">
              <div>
                Report ID: DEMO-2024-001 • Generated by InspectIQ AI
              </div>
              <div>
                Page 1 of 1
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* PDF Bottom Info */}
      <div className="bg-gray-900 border border-white/10 rounded-b-xl p-4 text-center">
        <p className="text-sm text-gray-400">
          This is a sample report. Actual reports include photos, detailed analysis, and more.
        </p>
      </div>
    </div>
  )
}
