import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import MarketingNav from '../components/MarketingNav'
import PDFReportPreview from '../components/PDFReportPreview'
import { 
  ArrowLeft, 
  Download, 
  Share2, 
  Calendar, 
  MapPin, 
  User,
  AlertCircle,
  CheckCircle,
  Camera,
  FileText,
  ArrowRight
} from 'lucide-react'

export default function DemoReport() {
  const navigate = useNavigate()
  const [selectedRoom, setSelectedRoom] = useState<string | null>(null)

  const inspection = {
    id: 'DEMO-2025-001',
    property: {
      address: '123 Main Street, Apt 4B',
      city: 'San Francisco',
      state: 'CA',
      zip: '94102',
      type: 'Apartment'
    },
    date: 'January 15, 2025',
    inspector: 'John Smith',
    type: 'Move-In Inspection',
    summary: {
      totalRooms: 4,
      totalPhotos: 18,
      totalIssues: 12,
      critical: 2,
      moderate: 5,
      minor: 5
    },
    rooms: [
      {
        id: 'living-room',
        name: 'Living Room',
        photos: 4,
        issues: [
          { severity: 'critical', text: 'Cracked window pane in north-facing window', location: 'North wall' },
          { severity: 'moderate', text: 'Paint chipping on baseboards', location: 'East wall' },
          { severity: 'minor', text: 'Scuff marks on wall near door', location: 'Entry' }
        ]
      },
      {
        id: 'kitchen',
        name: 'Kitchen',
        photos: 6,
        issues: [
          { severity: 'moderate', text: 'Loose cabinet door handle', location: 'Upper cabinets' },
          { severity: 'moderate', text: 'Grout discoloration around sink', location: 'Countertop' },
          { severity: 'minor', text: 'Dusty exhaust vent', location: 'Ceiling' },
          { severity: 'minor', text: 'Minor scratches on countertop', location: 'Near stove' }
        ]
      },
      {
        id: 'bedroom',
        name: 'Master Bedroom',
        photos: 3,
        issues: [
          { severity: 'moderate', text: 'Carpet stains near closet', location: 'Floor' },
          { severity: 'minor', text: 'Small nail holes in wall', location: 'West wall' }
        ]
      },
      {
        id: 'bathroom',
        name: 'Bathroom',
        photos: 5,
        issues: [
          { severity: 'critical', text: 'Water damage visible on ceiling', location: 'Ceiling above shower' },
          { severity: 'moderate', text: 'Loose tile near bathtub', location: 'Floor' },
          { severity: 'moderate', text: 'Mold growth in shower grout', location: 'Shower' }
        ]
      }
    ],
    aiAnalysis: {
      overallCondition: 'Fair',
      estimatedRepairCost: '$800 - $1,200',
      urgentItems: 2,
      recommendations: [
        'Address water damage in bathroom immediately to prevent further deterioration',
        'Replace cracked window pane for security and energy efficiency',
        'Clean and reseal bathroom grout to prevent mold growth',
        'Repair or replace loose cabinet hardware'
      ]
    }
  }

  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case 'critical': return 'text-red-400 bg-red-500/10 border-red-500/20'
      case 'moderate': return 'text-orange-400 bg-orange-500/10 border-orange-500/20'
      case 'minor': return 'text-yellow-400 bg-yellow-500/10 border-yellow-500/20'
      default: return 'text-gray-400 bg-gray-500/10 border-gray-500/20'
    }
  }

  const getSeverityIcon = (severity: string) => {
    return severity === 'critical' ? AlertCircle : CheckCircle
  }

  return (
    <div className="min-h-screen bg-black text-white">
      <MarketingNav />
      
      <div className="pt-24 pb-12 px-4">
        <div className="max-w-7xl mx-auto">
          {/* Header */}
          <div className="mb-8">
            <button
              onClick={() => navigate('/')}
              className="inline-flex items-center text-gray-400 hover:text-white mb-4 transition-colors"
            >
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Home
            </button>
            
            <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4">
              <div>
                <div className="inline-flex items-center space-x-2 bg-blue-500/10 border border-blue-500/20 px-3 py-1 rounded-full text-sm mb-3">
                  <FileText className="w-4 h-4 text-blue-400" />
                  <span className="text-blue-400">Sample Report</span>
                </div>
                <h1 className="text-4xl md:text-5xl font-bold mb-2">
                  Inspection Report
                </h1>
                <p className="text-gray-400 text-lg">
                  Explore a complete inspection report generated by InspectIQ
                </p>
              </div>
              
              <div className="flex flex-col sm:flex-row gap-3">
                <button className="px-6 py-3 bg-white/10 border border-white/20 rounded-lg hover:bg-white/20 transition-colors flex items-center justify-center">
                  <Share2 className="w-5 h-5 mr-2" />
                  Share
                </button>
                <button className="px-6 py-3 bg-gradient-to-r from-blue-600 to-purple-600 rounded-lg font-semibold hover:scale-105 transition-transform flex items-center justify-center">
                  <Download className="w-5 h-5 mr-2" />
                  Download PDF
                </button>
              </div>
            </div>
          </div>

          <div className="grid lg:grid-cols-3 gap-8">
            {/* Main Content */}
            <div className="lg:col-span-2 space-y-6">
              {/* Property Info */}
              <div className="bg-white/5 border border-white/10 rounded-2xl p-6">
                <h2 className="text-2xl font-bold mb-4">Property Information</h2>
                <div className="grid md:grid-cols-2 gap-4">
                  <div className="flex items-start space-x-3">
                    <MapPin className="w-5 h-5 text-blue-400 mt-1" />
                    <div>
                      <div className="text-sm text-gray-400">Address</div>
                      <div className="font-semibold">{inspection.property.address}</div>
                      <div className="text-sm text-gray-400">
                        {inspection.property.city}, {inspection.property.state} {inspection.property.zip}
                      </div>
                    </div>
                  </div>
                  <div className="flex items-start space-x-3">
                    <Calendar className="w-5 h-5 text-blue-400 mt-1" />
                    <div>
                      <div className="text-sm text-gray-400">Inspection Date</div>
                      <div className="font-semibold">{inspection.date}</div>
                    </div>
                  </div>
                  <div className="flex items-start space-x-3">
                    <User className="w-5 h-5 text-blue-400 mt-1" />
                    <div>
                      <div className="text-sm text-gray-400">Inspector</div>
                      <div className="font-semibold">{inspection.inspector}</div>
                    </div>
                  </div>
                  <div className="flex items-start space-x-3">
                    <FileText className="w-5 h-5 text-blue-400 mt-1" />
                    <div>
                      <div className="text-sm text-gray-400">Type</div>
                      <div className="font-semibold">{inspection.type}</div>
                    </div>
                  </div>
                </div>
              </div>

              {/* Summary Stats */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                <div className="bg-white/5 border border-white/10 rounded-xl p-4 text-center">
                  <div className="text-3xl font-bold text-blue-400">{inspection.summary.totalRooms}</div>
                  <div className="text-sm text-gray-400 mt-1">Rooms</div>
                </div>
                <div className="bg-white/5 border border-white/10 rounded-xl p-4 text-center">
                  <div className="text-3xl font-bold text-purple-400">{inspection.summary.totalPhotos}</div>
                  <div className="text-sm text-gray-400 mt-1">Photos</div>
                </div>
                <div className="bg-white/5 border border-white/10 rounded-xl p-4 text-center">
                  <div className="text-3xl font-bold text-red-400">{inspection.summary.critical}</div>
                  <div className="text-sm text-gray-400 mt-1">Critical</div>
                </div>
                <div className="bg-white/5 border border-white/10 rounded-xl p-4 text-center">
                  <div className="text-3xl font-bold text-orange-400">{inspection.summary.moderate}</div>
                  <div className="text-sm text-gray-400 mt-1">Moderate</div>
                </div>
              </div>

              {/* Rooms */}
              <div className="bg-white/5 border border-white/10 rounded-2xl p-6">
                <h2 className="text-2xl font-bold mb-4">Room-by-Room Findings</h2>
                <div className="space-y-4">
                  {inspection.rooms.map((room) => (
                    <div
                      key={room.id}
                      className={`border rounded-xl p-4 transition-all cursor-pointer ${
                        selectedRoom === room.id
                          ? 'bg-white/10 border-blue-500/50'
                          : 'bg-white/5 border-white/10 hover:border-white/20'
                      }`}
                      onClick={() => setSelectedRoom(selectedRoom === room.id ? null : room.id)}
                    >
                      <div className="flex items-center justify-between mb-3">
                        <div className="flex items-center space-x-3">
                          <Camera className="w-5 h-5 text-blue-400" />
                          <h3 className="text-xl font-bold">{room.name}</h3>
                        </div>
                        <div className="flex items-center space-x-4 text-sm">
                          <span className="text-gray-400">{room.photos} photos</span>
                          <span className={`px-3 py-1 rounded-full ${
                            room.issues.length > 0 ? 'bg-orange-500/20 text-orange-400' : 'bg-green-500/20 text-green-400'
                          }`}>
                            {room.issues.length} issues
                          </span>
                        </div>
                      </div>
                      
                      {selectedRoom === room.id && (
                        <div className="mt-4 space-y-3 border-t border-white/10 pt-4">
                          {room.issues.map((issue, index) => {
                            const Icon = getSeverityIcon(issue.severity)
                            return (
                              <div
                                key={index}
                                className={`flex items-start space-x-3 p-3 rounded-lg border ${getSeverityColor(issue.severity)}`}
                              >
                                <Icon className="w-5 h-5 mt-0.5 flex-shrink-0" />
                                <div className="flex-1">
                                  <div className="font-medium mb-1">{issue.text}</div>
                                  <div className="text-sm opacity-75">Location: {issue.location}</div>
                                </div>
                                <span className="text-xs uppercase font-semibold px-2 py-1 rounded">
                                  {issue.severity}
                                </span>
                              </div>
                            )
                          })}
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Sidebar */}
            <div className="space-y-6">
              {/* AI Analysis */}
              <div className="bg-gradient-to-br from-purple-500/10 to-pink-500/10 border border-purple-500/20 rounded-2xl p-6">
                <h3 className="text-xl font-bold mb-4 flex items-center">
                  <span className="text-2xl mr-2">🤖</span>
                  AI Analysis
                </h3>
                <div className="space-y-4">
                  <div>
                    <div className="text-sm text-gray-400 mb-1">Overall Condition</div>
                    <div className="text-2xl font-bold text-orange-400">{inspection.aiAnalysis.overallCondition}</div>
                  </div>
                  <div>
                    <div className="text-sm text-gray-400 mb-1">Est. Repair Cost</div>
                    <div className="text-xl font-bold">{inspection.aiAnalysis.estimatedRepairCost}</div>
                  </div>
                  <div>
                    <div className="text-sm text-gray-400 mb-1">Urgent Items</div>
                    <div className="text-xl font-bold text-red-400">{inspection.aiAnalysis.urgentItems}</div>
                  </div>
                </div>
              </div>

              {/* Recommendations */}
              <div className="bg-white/5 border border-white/10 rounded-2xl p-6">
                <h3 className="text-xl font-bold mb-4">Recommendations</h3>
                <ul className="space-y-3">
                  {inspection.aiAnalysis.recommendations.map((rec, index) => (
                    <li key={index} className="flex items-start space-x-2">
                      <CheckCircle className="w-5 h-5 text-green-400 mt-0.5 flex-shrink-0" />
                      <span className="text-sm text-gray-300">{rec}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* CTA */}
              <div className="bg-gradient-to-br from-blue-500/10 to-purple-500/10 border border-blue-500/20 rounded-2xl p-6 text-center">
                <h3 className="text-xl font-bold mb-2">Like What You See?</h3>
                <p className="text-gray-400 text-sm mb-4">
                  Create your own professional inspection reports in minutes
                </p>
                <button
                  onClick={() => navigate('/register')}
                  className="w-full px-6 py-3 bg-gradient-to-r from-blue-600 to-purple-600 rounded-lg font-semibold hover:scale-105 transition-transform flex items-center justify-center"
                >
                  Start Free Trial
                  <ArrowRight className="w-5 h-5 ml-2" />
                </button>
                <p className="text-xs text-gray-500 mt-3">No credit card required</p>
              </div>
            </div>
          </div>
        </div>

        {/* PDF Preview Section */}
        <div className="mt-20">
          <div className="text-center mb-12">
            <h2 className="text-4xl font-bold mb-4">
              Professional <span className="text-blue-400">PDF Report</span>
            </h2>
            <p className="text-xl text-gray-400">
              See how your inspection looks as a downloadable PDF
            </p>
          </div>
          <PDFReportPreview />
        </div>
      </div>
    </div>
  )
}
